# Operator
- type: startingGear
  id: CentCommOperatorGearQillu
  equipment:
    eyes: ClothingEyesGlassesCommand
    shoes: ClothingShoesBootsCombatFilled
    gloves: ClothingHandsGlovesCentcomQillu
    outerClothing: ClothingOuterArmorCentcomChestplateQillu
    id: CentcomOperatorPDAQillu
    ears: ClothingHeadsetAltCentCom
    belt: WeaponPistolN1984
  storage:
    back:
    - RubberStampCentcom

# Inspector
- type: job
  id: LustCentCommInspector
  name: job-name-centcomins
  description: job-description-centcomins
  playTimeTracker: JobLustCentCommInspector
  requirements:
  - !type:DiscordRoleRequirement
  weight: 30
  setPreference: true
  startingGear: CentCommOperatorGearQillu
  icon: "JobIconNanotrasen"
  overrideConsoleVisibility: false
  supervisors: job-supervisors-centcom
  radioBold: true
  alwaysUseSpawner: true
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]
  - !type:AddComponentSpecial
    components:
    - type: ParadoxCloneImmune

# Chief of staff
- type: job
  id: LustCentCommChiefOfStaff
  name: job-name-centcomchief
  description: job-description-centcomchief
  playTimeTracker: JobLustCentCommChiefOfStaff
  requirements:
  - !type:DiscordRoleRequirement
  weight: 60
  setPreference: true
  startingGear: CentCommOperatorGearQillu
  icon: "JobIconNanotrasen"
  overrideConsoleVisibility: false
  supervisors: job-supervisors-centcom
  radioBold: true
  alwaysUseSpawner: true
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]
  - !type:AddComponentSpecial
    components:
    - type: ParadoxCloneImmune

# Intern
- type: job
  id: LustCentCommIntern
  name: job-name-centcomint
  description: job-description-centcomint
  playTimeTracker: JobLustCentCommIntern
  requirements:
  - !type:DiscordRoleRequirement
  weight: 10
  setPreference: true
  startingGear: CentCommOperatorGearQillu
  icon: "JobIconNanotrasen"
  overrideConsoleVisibility: false
  supervisors: job-supervisors-centcom
  radioBold: true
  alwaysUseSpawner: true
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]
  - !type:AddComponentSpecial
    components:
    - type: ParadoxCloneImmune


# ID Operator
- type: job
  id: LustCentCommIDOperator
  name: job-name-centcomid
  description: job-description-centcomid
  playTimeTracker: JobLustCentCommIDOperator
  requirements:
  - !type:DiscordRoleRequirement
  weight: 70
  setPreference: true
  startingGear: CentCommOperatorGearQillu
  icon: "JobIconNanotrasen"
  overrideConsoleVisibility: false
  supervisors: job-supervisors-centcom
  radioBold: true
  alwaysUseSpawner: true
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]
  - !type:AddComponentSpecial
    components:
    - type: ParadoxCloneImmune


# SpecOps Operator
- type: job
  id: LustCentCommSpecOpsOperator
  name: job-name-centcomso
  description: job-description-centcomso
  playTimeTracker: JobLustCentCommSpecOpsOperator
  requirements:
  - !type:DiscordRoleRequirement
  weight: 40
  setPreference: true
  startingGear: LustCentCommSpecOpsOperatorGearQillu
  icon: "JobIconNanotrasen"
  overrideConsoleVisibility: false
  supervisors: job-supervisors-centcom
  radioBold: true
  alwaysUseSpawner: true
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]
  - !type:AddComponentSpecial
    components:
    - type: ParadoxCloneImmune

- type: startingGear
  id: LustCentCommSpecOpsOperatorGearQillu
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficerBlack
    head: ClothingHeadCapCentcomBlack
    shoes: ClothingShoesCentcomBlack
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorBlack
    id: CentcomOperatorPDA
    ears: ClothingHeadsetCentCom
    belt: WeaponPistolN1984
    back: ClothingBackpackSatchelLeather
  storage:
    back:
    - RubberStampCentcom #!
